// Code generated by protoc-gen-go. DO NOT EDIT.
// source: food-factory.proto

package proto

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type FoodResponse struct {
	Code                 string   `protobuf:"bytes,1,opt,name=code,proto3" json:"code,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *FoodResponse) Reset()         { *m = FoodResponse{} }
func (m *FoodResponse) String() string { return proto.CompactTextString(m) }
func (*FoodResponse) ProtoMessage()    {}
func (*FoodResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_5a177e2916680b50, []int{0}
}

func (m *FoodResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_FoodResponse.Unmarshal(m, b)
}
func (m *FoodResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_FoodResponse.Marshal(b, m, deterministic)
}
func (m *FoodResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_FoodResponse.Merge(m, src)
}
func (m *FoodResponse) XXX_Size() int {
	return xxx_messageInfo_FoodResponse.Size(m)
}
func (m *FoodResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_FoodResponse.DiscardUnknown(m)
}

var xxx_messageInfo_FoodResponse proto.InternalMessageInfo

func (m *FoodResponse) GetCode() string {
	if m != nil {
		return m.Code
	}
	return ""
}

type FoodReply struct {
	Code                 string   `protobuf:"bytes,1,opt,name=code,proto3" json:"code,omitempty"`
	Name                 string   `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Price                int64    `protobuf:"varint,3,opt,name=price,proto3" json:"price,omitempty"`
	Other                string   `protobuf:"bytes,4,opt,name=other,proto3" json:"other,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *FoodReply) Reset()         { *m = FoodReply{} }
func (m *FoodReply) String() string { return proto.CompactTextString(m) }
func (*FoodReply) ProtoMessage()    {}
func (*FoodReply) Descriptor() ([]byte, []int) {
	return fileDescriptor_5a177e2916680b50, []int{1}
}

func (m *FoodReply) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_FoodReply.Unmarshal(m, b)
}
func (m *FoodReply) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_FoodReply.Marshal(b, m, deterministic)
}
func (m *FoodReply) XXX_Merge(src proto.Message) {
	xxx_messageInfo_FoodReply.Merge(m, src)
}
func (m *FoodReply) XXX_Size() int {
	return xxx_messageInfo_FoodReply.Size(m)
}
func (m *FoodReply) XXX_DiscardUnknown() {
	xxx_messageInfo_FoodReply.DiscardUnknown(m)
}

var xxx_messageInfo_FoodReply proto.InternalMessageInfo

func (m *FoodReply) GetCode() string {
	if m != nil {
		return m.Code
	}
	return ""
}

func (m *FoodReply) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *FoodReply) GetPrice() int64 {
	if m != nil {
		return m.Price
	}
	return 0
}

func (m *FoodReply) GetOther() string {
	if m != nil {
		return m.Other
	}
	return ""
}

func init() {
	proto.RegisterType((*FoodResponse)(nil), "proto.FoodResponse")
	proto.RegisterType((*FoodReply)(nil), "proto.FoodReply")
}

func init() {
	proto.RegisterFile("food-factory.proto", fileDescriptor_5a177e2916680b50)
}

var fileDescriptor_5a177e2916680b50 = []byte{
	// 177 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0x12, 0x4a, 0xcb, 0xcf, 0x4f,
	0xd1, 0x4d, 0x4b, 0x4c, 0x2e, 0xc9, 0x2f, 0xaa, 0xd4, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0x62,
	0x05, 0x53, 0x4a, 0x4a, 0x5c, 0x3c, 0x6e, 0xf9, 0xf9, 0x29, 0x41, 0xa9, 0xc5, 0x05, 0xf9, 0x79,
	0xc5, 0xa9, 0x42, 0x42, 0x5c, 0x2c, 0xc9, 0xf9, 0x29, 0xa9, 0x12, 0x8c, 0x0a, 0x8c, 0x1a, 0x9c,
	0x41, 0x60, 0xb6, 0x52, 0x3c, 0x17, 0x27, 0x44, 0x4d, 0x41, 0x4e, 0x25, 0x36, 0x05, 0x20, 0xb1,
	0xbc, 0xc4, 0xdc, 0x54, 0x09, 0x26, 0x88, 0x18, 0x88, 0x2d, 0x24, 0xc2, 0xc5, 0x5a, 0x50, 0x94,
	0x99, 0x9c, 0x2a, 0xc1, 0xac, 0xc0, 0xa8, 0xc1, 0x1c, 0x04, 0xe1, 0x80, 0x44, 0xf3, 0x4b, 0x32,
	0x52, 0x8b, 0x24, 0x58, 0xc0, 0x4a, 0x21, 0x1c, 0x23, 0x57, 0x2e, 0x6e, 0x90, 0x05, 0x6e, 0x10,
	0x07, 0x0a, 0x99, 0x71, 0x71, 0xbb, 0xa7, 0x96, 0x80, 0x44, 0x9c, 0x2a, 0x3d, 0x5d, 0x84, 0x84,
	0x21, 0x2e, 0xd6, 0x43, 0x76, 0xa7, 0x94, 0x00, 0x8a, 0x60, 0x41, 0x4e, 0xa5, 0x12, 0x43, 0x12,
	0x1b, 0x58, 0xc8, 0x18, 0x10, 0x00, 0x00, 0xff, 0xff, 0x7a, 0xed, 0xac, 0x73, 0xef, 0x00, 0x00,
	0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConnInterface

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion6

// FoodFactoryClient is the client API for FoodFactory service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type FoodFactoryClient interface {
	GetFoodByID(ctx context.Context, in *FoodResponse, opts ...grpc.CallOption) (*FoodReply, error)
}

type foodFactoryClient struct {
	cc grpc.ClientConnInterface
}

func NewFoodFactoryClient(cc grpc.ClientConnInterface) FoodFactoryClient {
	return &foodFactoryClient{cc}
}

func (c *foodFactoryClient) GetFoodByID(ctx context.Context, in *FoodResponse, opts ...grpc.CallOption) (*FoodReply, error) {
	out := new(FoodReply)
	err := c.cc.Invoke(ctx, "/proto.FoodFactory/GetFoodByID", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// FoodFactoryServer is the server API for FoodFactory service.
type FoodFactoryServer interface {
	GetFoodByID(context.Context, *FoodResponse) (*FoodReply, error)
}

// UnimplementedFoodFactoryServer can be embedded to have forward compatible implementations.
type UnimplementedFoodFactoryServer struct {
}

func (*UnimplementedFoodFactoryServer) GetFoodByID(ctx context.Context, req *FoodResponse) (*FoodReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetFoodByID not implemented")
}

func RegisterFoodFactoryServer(s *grpc.Server, srv FoodFactoryServer) {
	s.RegisterService(&_FoodFactory_serviceDesc, srv)
}

func _FoodFactory_GetFoodByID_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(FoodResponse)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FoodFactoryServer).GetFoodByID(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.FoodFactory/GetFoodByID",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FoodFactoryServer).GetFoodByID(ctx, req.(*FoodResponse))
	}
	return interceptor(ctx, in, info, handler)
}

var _FoodFactory_serviceDesc = grpc.ServiceDesc{
	ServiceName: "proto.FoodFactory",
	HandlerType: (*FoodFactoryServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetFoodByID",
			Handler:    _FoodFactory_GetFoodByID_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "food-factory.proto",
}
